In [1]:
n=1000

In [2]:
import numpy as np

In [3]:
draws=np.random.randint(0,2,size=n)

In [4]:
draws

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [5]:
steps=np.where(draws>0,1,-1)

In [6]:
steps

array([ 1,  1,  1, -1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1, -1,
        1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,
       -1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,
       -1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1,  1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1,
        1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1, -1, -1,
        1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1,
       -1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1, -1,
       -1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1,
        1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1,
        1,  1, -1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,
       -1,  1, -1,  1, -1

In [7]:
walk=steps.cumsum()

In [8]:
walk

array([  1,   2,   3,   2,   3,   4,   5,   4,   3,   4,   3,   4,   5,
         4,   5,   4,   3,   4,   5,   4,   5,   4,   3,   4,   3,   4,
         5,   4,   3,   4,   5,   4,   5,   4,   3,   2,   3,   2,   3,
         4,   5,   4,   5,   4,   5,   6,   7,   8,   7,   8,   9,   8,
         7,   6,   5,   6,   5,   4,   5,   6,   7,   6,   7,   6,   5,
         4,   3,   2,   1,   0,  -1,   0,  -1,  -2,  -3,  -4,  -3,  -2,
        -1,  -2,  -1,  -2,  -3,  -2,  -3,  -2,  -3,  -2,  -3,  -2,  -1,
        -2,  -3,  -2,  -1,  -2,  -3,  -4,  -5,  -4,  -5,  -6,  -5,  -6,
        -7,  -6,  -7,  -6,  -7,  -6,  -5,  -6,  -7,  -8,  -7,  -6,  -5,
        -6,  -7,  -8,  -9, -10, -11, -12, -11, -12, -13, -12, -11, -12,
       -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -21, -20, -19,
       -20, -19, -20, -21, -22, -21, -20, -21, -20, -21, -22, -21, -20,
       -19, -20, -21, -20, -21, -20, -21, -20, -21, -20, -21, -20, -21,
       -22, -23, -24, -23, -24, -23, -24, -25, -26, -25, -26, -2

In [9]:
walk.min()

-63

In [10]:
walk.max()

9

In [11]:
np.abs(walk)>10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,

In [12]:
(np.abs(walk)>10).argmax()

122

In [13]:
w=5000

In [14]:
d=np.random.randint(0,2,size=(w,n))

In [15]:
s=np.where(d>0,1,-1)

In [16]:
w=s.cumsum(1)

In [17]:
w

array([[  1,   2,   3, ..., -26, -25, -24],
       [ -1,   0,  -1, ...,  34,  33,  34],
       [ -1,   0,   1, ...,  36,  37,  38],
       ...,
       [  1,   2,   3, ..., -46, -47, -48],
       [ -1,  -2,  -3, ...,  -4,  -3,  -4],
       [ -1,  -2,  -1, ...,   6,   7,   6]], dtype=int32)

In [18]:
w.shape

(5000, 1000)

In [19]:
w.max(),w.min()

(126, -126)

In [20]:
hit30=(np.abs(w)>=30).any(1)

In [21]:
hit30,len(hit30),hit30.sum()

(array([ True,  True,  True, ...,  True,  True, False]), 5000, 3363)

In [22]:
crossing_times=(np.abs(w[hit30])>=30).argmax(1)

In [23]:
crossing_times

array([987, 909, 253, ..., 253, 567, 385], dtype=int32)

In [24]:
crossing_times.mean()

512.2946773713946

In [25]:
len(crossing_times)

3363