In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [3]:
obj=Series([1,2,-2,3])

In [4]:
obj

0    1
1    2
2   -2
3    3
dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj.values

array([ 1,  2, -2,  3], dtype=int64)

In [7]:
obj2=Series([1,2,3,4],index=['a','d','c','e'])

In [8]:
obj2

a    1
d    2
c    3
e    4
dtype: int64

In [9]:
obj2.index

Index(['a', 'd', 'c', 'e'], dtype='object')

In [10]:
obj2['d']=-2

In [11]:
obj2>0

a     True
d    False
c     True
e     True
dtype: bool

In [12]:
obj2[obj2>0]

a    1
c    3
e    4
dtype: int64

In [13]:
'c' in obj2

True

In [14]:
'3' in obj2

False

In [15]:
obj2.name='janedoe'

In [16]:
obj2

a    1
d   -2
c    3
e    4
Name: janedoe, dtype: int64

In [17]:
d2={'a':2,'b':3,'c':3}

In [18]:
d2

{'a': 2, 'b': 3, 'c': 3}

In [19]:
obj3=Series(d2)

In [20]:
obj3

a    2
b    3
c    3
dtype: int64

In [21]:
obj2+obj3

a    3.0
b    NaN
c    6.0
d    NaN
e    NaN
dtype: float64

In [23]:
import numpy as np

In [24]:
arr = np.arange(20.).reshape(4, 5)

In [25]:
arr[0]

array([0., 1., 2., 3., 4.])

In [26]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 5.,  5.,  5.,  5.,  5.],
       [10., 10., 10., 10., 10.],
       [15., 15., 15., 15., 15.]])

In [27]:
frame = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'), index=list('xyza'))

In [28]:
frame

b   d   e
x  0   1   2
y  3   4   5
z  6   7   8
a  9  10  11

In [29]:
series = frame.iloc[0]

In [30]:
series

b    0
d    1
e    2
Name: x, dtype: int32

In [31]:
frame - series

b  d  e
x  0  0  0
y  3  3  3
z  6  6  6
a  9  9  9

In [32]:
series = frame['e']

In [33]:
series

x     2
y     5
z     8
a    11
Name: e, dtype: int32

In [34]:
np.abs(frame.sub(series, axis=0))

b  d  e
x  2  1  0
y  2  1  0
z  2  1  0
a  2  1  0

In [35]:
frame2 = DataFrame(np.random.randn(4,3),index=list('abcd'),columns=list('xyz'))

In [36]:
frame2

x         y         z
a -0.168147  0.455874  1.043613
b  0.539960  0.941816  0.516952
c -0.538331 -0.541433  0.342055
d -0.347576  1.754288 -1.138665

In [37]:
f = lambda x: x.max() - x.min()

In [38]:
frame2.apply(f)

x    1.078291
y    2.295721
z    2.182278
dtype: float64

In [39]:
frame2.apply(f, axis=1)

a    1.211760
b    0.424864
c    0.883488
d    2.892953
dtype: float64

In [40]:
series.sort_index()

a    11
x     2
y     5
z     8
Name: e, dtype: int32

In [41]:
series

x     2
y     5
z     8
a    11
Name: e, dtype: int32

In [42]:
series.sort_values(ascending=False)

a    11
z     8
y     5
x     2
Name: e, dtype: int32

In [43]:
frame2.sort_values(by=['x','y'])

x         y         z
c -0.538331 -0.541433  0.342055
d -0.347576  1.754288 -1.138665
a -0.168147  0.455874  1.043613
b  0.539960  0.941816  0.516952

In [44]:
obj = Series([7, -5, 7, 4, 2, 0, 4])

In [45]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [46]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [47]:
df=DataFrame(np.random.randn(4,3), index=list('aabc'))

In [48]:
df

0         1         2
a -0.139248 -2.519924  1.962513
a -1.609105 -1.153353  0.901275
b -1.143167  0.658964 -0.048688
c  0.681653  1.204347  0.535685

In [49]:
df.loc['a']

0         1         2
a -0.139248 -2.519924  1.962513
a -1.609105 -1.153353  0.901275

In [50]:
df.describe()

0         1         2
count  4.000000  4.000000  4.000000
mean  -0.552467 -0.452491  0.837696
std    1.026192  1.707428  0.845802
min   -1.609105 -2.519924 -0.048688
25%   -1.259651 -1.494995  0.389592
50%   -0.641207 -0.247194  0.718480
75%    0.065977  0.795310  1.166585
max    0.681653  1.204347  1.962513